### ISSUE TITLE
createReadStream/createWriteStream not emitting 'open' events?

### ISSUE THREAD

**Issue by eugirdor** [sakren/node-fs-mock#9]
As far as I can tell, the createReadStream and createWriteStream methods are not emitting 'open' events when they successfully open their respective streams.

**Comment by sakren** [comment]
Oops.. Thanks, do you want to create PR?

**Comment by david-rodrigue** [comment]
Sure, I can probably create one in the next couple of days.

**Comment by sakren** [comment]
That would be great, thank you :)

**Comment by eugirdor** [comment]
I issued a pull request, but it seems to fail on the build server for Node 0.9 complaining about the version of CoffeeScript.  I didn't change the version it was using.
